[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2024"

[lints.rust]
elided_lifetimes_in_paths = "deny"

[dependencies]
cgmath = { version = "0.18.0" }
encase = { version = "0.10.0", features = ["cgmath"] }
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"
